# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2095d8e25dc8f6a7c2d792f9b09940fb774e15fbbf3593cb88d2f59a2823eef9f441fa50971b9c6daf9a261bcfa91755199c607592181f86067c94f38288f8c5

test:
  secret_key_base: 6ea168cb5aa2436f3f0838bded6f2ee03d475370b89d02c27ef5dc2ffa92b657db6c0525ee787b12f25c8e24a2ae5b348ecd576b5a32818d4ef6eb60953d4710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
